# Generated by Django 5.2.7 on 2025-11-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city_zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('USA', 'United States of America'), ('CAN', 'Canada'), ('MEX', 'Mexico'), ('GBR', 'United Kingdom'), ('FRA', 'France')])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city_zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('USA', 'United States of America'), ('CAN', 'Canada'), ('MEX', 'Mexico'), ('GBR', 'United Kingdom'), ('FRA', 'France')])),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.company')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
