# Generated by Django 5.2.7 on 2025-11-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Company',
        ),
    ]
