# Generated by Django 5.2.7 on 2025-11-04 11:28

import django.db.models.deletion
import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_client_address_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('USA', 'United States of America'), ('CAN', 'Canada'), ('MEX', 'Mexico'), ('GBR', 'United Kingdom'), ('FRA', 'France')], max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('USA', 'United States of America'), ('CAN', 'Canada'), ('MEX', 'Mexico'), ('GBR', 'United Kingdom'), ('FRA', 'France')], max_length=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=invoice.models.Default_due_date),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
