# Generated by Django 5.2.7 on 2025-11-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_client_country_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoice.invoice'),
        ),
    ]
