# Generated by Django 5.2.7 on 2025-11-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoiceitems_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Company',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice'),
        ),
    ]
