# Generated by Django 5.2.7 on 2025-11-04 12:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_invoice_date_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
