# Generated by Django 5.2.7 on 2025-11-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_tax_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='tax',
            new_name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_percentage',
        ),
    ]
