# Generated by Django 5.2.7 on 2025-11-04 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_rename_tax_invoiceitems_tax_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='tax_percentage',
            new_name='tax',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
