# Generated by Django 5.2.7 on 2025-11-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoice_subtotal_invoice_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='tax',
            new_name='tax_percentage',
        ),
    ]
