# Generated by Django 5.2.7 on 2025-11-04 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_rename_tax_invoiceitems_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
