# Generated by Django 5.2.7 on 2025-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_remove_client_name_invoiceitem_delete_invoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
