# Generated by Django 5.2.7 on 2025-11-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_company_logo_invoice_invoice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to='uploads'),
        ),
    ]
